### ISSUE TITLE
Bad argument namespace scoping

### ISSUE THREAD

**Issue by vibraphone** [OpenGeoscience/shiboken#2]
Shiboken cannot wrap some methods, apparently because it resolves argument namespace-scopes in the wrong order. I don't even want the method wrapped, but am unable to stop shiboken from trying. Do any of you have an idea of how to fix this, or where in shiboken the problem exists? Here is an example of the problem:

``` c++
class X;
namespace Y {

  class X; // Not the same as ::X

  class Z
  {
  protected:
    static Y::X convertOldToNew(::X* old);
  };
}
```

The problem is that shiboken generates wrapper code like this:

``` c++
class Y_ZWrapper : public Y::Z
{
public:
    Y_ZWrapper();
    inline static Y::X convertOldToNew_protected(Y::X * arg__1) { return Y::Z::convertOldToNew(arg__1); }
};
```

which of course fails to compile because the argument type for Y_ZWrapper::convertOldToNew_protected() doesn't match Y::Z::convertOldToNew().

I've tried adding

``` xml
  <modify-function remove="all" signature="convertOldToNew(::X* old);"/>
```

and even

``` xml
  <modify-function remove="all" signature="convertOldToNew(Y::X* old);"/>
```

but shiboken stubbornly insists on generating the bad code regardless.

**Comment by mwoehlke** [comment]
1. This is a fork of Shiboken. You really should ask upstream these sorts of questions first; see http://qt-project.org/wiki/PySide.
2. &lt;modify&gt; is not the correct directive to exclude a function. What wou want is a &lt;rejection&gt;. (Unfortunately this doesn't seem to be documented; I'd check the source, especially the test typesystems, for example usage.)

**Comment by vibraphone** [comment]
Thanks. Rejection gets things working for me. I am leery of asking upstream without testing that upstream has the same issue.
